config/routes.rb
Rails.application.routes.draw do
  get 'pages/experience', :as=>:experience

  get 'pages/sewing', :as=>:sewing

  get 'pages/robots', :as=>:robots

  get 'pages/makerfaire', :as=>:makerfaire

  get 'pages/projects', :as=>:projects

  get 'pages/resume', :as=>:resume

  get 'welcome/index'

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	require 'openssl'
	OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
  def experience
  end

  def sewing
  end

  def robots
  end

  def makerfaire
  end

  def projects
  end

  def resume
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<%= nav_bar fixed: :top, brand: "", responsive: true do %>
	<%= menu_group do %>
        <%= menu_item "Home", root_path, :class=>"nav-bigger" %>
		<%= menu_item "Experience", experience_path, :class=>"nav-bigger"%>
        <%= menu_item "Robotics", robots_path, :class=>"nav-bigger" %>
        <%= menu_item "Sewing", sewing_path, :class=>"nav-bigger" %>
		<%= menu_item "Coding Projects", projects_path, :class=>"nav-bigger" %>
        <%= menu_item "Maker Faire NC", makerfaire_path, :class=>"nav-bigger" %>
    <% end %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resume</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body style="padding-top: 50px">
	<%= render "layouts/nav"%>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/experience.html.erb
<h1 class="text-pink text-center">Experience</h1>
<div class="row">
	<h4>IBM Virtualization Team Lead <small>November 2013 - Present <span class="pull-right">Raleigh NC</span></small></h4>
	<div class="col-md-1">
	</div>
	<div class="col-md-11">
		  
		<p>As team lead, I facilitate inter-team communication ensuring that all tasks are covered, goals are achieved, requests are completed smoothly, and any issues are handled promptly.</p>
		<p>While the team is small with just six employees, the environment is expansive, supporting over 6500 Virtual Machines and over 800 Users.  Other aspects of my role as team lead involve interfacing with customers to fix problems, answer questions, and send official notifications.</p>
	</div>
</div>
<div class="row">
	<h4>IBM Software Developer <small>January 2012 - Present <span class="pull-right">Raleigh NC</span></small></h4>
	<div class="col-md-1">
	</div>
	<div class="col-md-11">
		<p>As a programmer for the virtulaization team, my main project has been a self-service Infrastructure as a Service (IaaS) provisioning solution called vLaunch. In addition to automated provisioning, the system also provides a billing and reporting dashboard for admins.  The system was primarily written in Ruby on Rails using Bootstrap, with some Java and Python thrown in for handling automation and interfacing with outside systems.</p>
		<p>As the primary developer for vLaunch, I have had to wear several hats to complete the project:
			<ul class="list-unstyled">
				<li><b>Database Designer:</b>  I designed a database to efficiently hold VM information and maintain records as well as allow dynamic creation of request types.</li>
				<li><b>Project Manager:</b> I planned and prioritized administrative and user feature requests along with working on the overall layout and design of the project.</li>
				<li><b>Developer:</b>  I built out all of the prioritized features and implemented bug fixes, usually within a matter of hours of being reported.</li>
				<li><b>Tester:</b> Squashed bugs from new code before the code has been pushed into production.  Performed impact analysis on code changes to determine how changes will affect the environment.</li>
			</ul>
		</p>
		<p>I also wrote a custom application which allowed my team to send communications targeted to specific groups of users.  For example, when Windows XP hit end of life, we could send emails to just the user base that still had Windows XP virtual machines.</p>
	</div>
</div>
<div class="row">
	<h4>IBM Software Intern <small> June 2010 - January 2012 <span class="pull-right">Raleigh NC</span></small></h4>
	<div class="col-md-1">
	</div>
	<div class="col-md-11">
		<p>While an intern at IBM, I wrote code for many different projects, mostly in Java.</p>
		<ul class="list-unstyled">
			<li><b>Online Password Reset</b> - A website which allowed our users to reset their Active Directory password. Previously, an admin had to reset it for them or they had to log directly into the Active Directory server, presenting a security vulnerability. </li>
			<li><b>MSDN Check</b> -  A script which ran weekly. It enabled our team to verify that anyone using Windows VMs had a valid licence. It also compared the owners of the VMs to a list of users currently employed. It reported users who had left, saving the company over a million dollars in reclaimed licences. To accomplish this, the program used Selenium to download a list from MSDN, parse it into new users and users who had left IBM, and then update the official LDAP group which tracked the users.  Lastly, it emailed out the list of users who had left IBM to the appropriate software license administrators. </li>
			<li><b>Bulk IP Address Requester</b> - A Java program which allowed virtualization admins to request a static IP address and associated hostname en mass. It could be given an array of unique names or a starting name, index and number of IPs to request.</li>
		</ul>
	</div>
</div>
<div class="row">
	<h4>Senior Design / Deutsche Bank Global Technology <small>August 2011 - December 2011 <span class="pull-right">Cary NC</span></small></h4>
	<div class="col-md-1">
	</div>
	<div class="col-md-11">
		<p>Designed and built a UI with HTML5 and CSS for a stock market trading game. The game allowed users to trade any stock on the market.  It utilized Yahoo's stock API so that prices were updated in near real-time. </p>
		<p>During this project, I acted as team lead to facilitate communications between the team and Deutsche Bank Global Technology (DBGT). I also helped prioritize the different tasks as determined in our weekly scrum meetings at DBGT.</p>
	</div>
</div>
<div class="row">
	<h4>Rudinos Pizza and Grinders Waitress <small>May 2008 - August 2008 <span class="pull-right">Cary NC</span></small></h4>
	<div class="col-md-1">
	</div>
	<div class="col-md-11">
		<p>For a summer after college I waitressed at a local pizza restaurant. I learned how to interact with customers to ensure a prompt and pleasant experience. </p>
	</div>
</div>
<div class="row">
	<h4>West Regional Library Page <small>August 2006 - June 2007 <span class="pull-right">Cary NC</span></small></h4>
	<div class="col-md-1">
	</div>
	<div class="col-md-11">
		<p>I worked at the local library while in high school checking books in, shelving them and reorganizing selves. </p>
	</div>
</div>

app/views/pages/makerfaire.html.erb
<h1 class="text-pink text-center">Maker Faire North Carolina</h1>
<div class="col-md-5">
	<p>
		Maker Faire North Carolina (MFNC) was a giant show-and-tell. Started in 2010, MFNC started out as a small event held at an abandoned department store building. By its last year in 2014, it was an event with over 6,000 makers and attendees.
	</p>
	<p>
		As the sponsor recruiter for MFNC, I was responsible for finding sponsors, onboarding them, and then ensuring they remained as sponsors for as long as possible.  After a sponsor was on board, I fulfilled all the duties as described by their sponsor contract, as well as continuing to follow up with any needs they might have had.
	</p>
	<p>
		On the weekend of the event, I helped run sales, coordinate volunteers, and perform other odd jobs. During the short breaks at event, it was a lot of fun to walk around and learn about everything from knitting to blacksmithing to jewelery making. 
	</p>
	<p>
		MFNC was an amazing event. Not only because it educated thousands of people, but also because I learned so much about working with a team, coordinating large events, and talking with professionals from a multitude of companies and sponsors.
	</p>

</div>
<div class="col-md-7">
	<div id="carousel-mfnc" class="carousel slide" data-ride="carousel" >
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#carousel-mfnc" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel-mfnc" data-slide-to="1"></li>
	    <li data-target="#carousel-mfnc" data-slide-to="2"></li>
		<li data-target="#carousel-mfnc" data-slide-to="3"></li>
		<li data-target="#carousel-mfnc" data-slide-to="4"></li>
		<li data-target="#carousel-mfnc" data-slide-to="5"></li>
	  </ol>

	  <!-- Wrapper for slides -->
	  <div class="carousel-inner" role="listbox" >
	    <div class="item active">
			<%=image_tag("LearnToSolder.jpg", alt:"Learn to Solder")%>
	      	<div class="carousel-caption">
	        	Learn to Solder booth at Maker Faire NC 2014
	      	</div>
	    </div>
	    <div class="item">
	      <%=image_tag("MFNC2012.jpg", alt:"Maker Faire NC 2012")%>
	      <div class="carousel-caption">
	        Maker Faire NC 2012
	      </div>
	    </div>
	    <div class="item">
	      <%=image_tag("MFNC2014.jpg", alt:"Maker Faire 2014")%>
	      <div class="carousel-caption">
	        Maker Faire 2014
	      </div>
	    </div>
	    <div class="item">
	      <%=image_tag("MFNC2014(2).jpg", alt:"Maker Faire 2014 Balloon Launch")%>
	      <div class="carousel-caption">
	        Maker Faire 2014 Balloon Launch
	      </div>
	    </div>
	    <div class="item">
	      <%=image_tag("PhotoBooth.jpg", alt:"Meg and Marshall at the Photo Booth")%>
	      <div class="carousel-caption">
	        Meg and Marshall at the Photo Booth, Maker Faire 2012
	      </div>
	    </div>
	    <div class="item">
	      <%=image_tag("Stamp.jpg", alt:"Maker Faire Stamp")%>
	      <div class="carousel-caption">
	        Maker Faire North Carolina
	      </div>
	    </div>
	  </div>

	  <!-- Controls -->
	  <a class="left carousel-control" href="#carousel-mfnc" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#carousel-mfnc" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
	<script>
	$('.carousel').carousel({
	  interval: 5000
	})
	</script>
</div>

app/views/pages/projects.html.erb
<h1 class="text-pink text-center">Coding Projects</h1>

<div class="row">
	<h4>Virtualization Launchpad - Management and Monitoring</h4>
	<div class="col-md-12">
		<%=image_tag("vLaunch.png", alt:"vLaunch", class:"col-md-6")%>
		<p>vLaunch is a user interface, billing and reporting tool to manage a virtualization environment. </p>
		<p>The real genious behind this program is the request setup. It enables admins to dynamically create request types. By simply choosing which tasks an action should have, admins can create entirely new request types with different required information for the user to fill in. This enables new automated tasks without the admins needing to change the base code. It also allows reuse of code. </p>
		<p>For example, an admin could create a task "Power on VM". Power on VM only requires the VM's name. They could then create a request type which is only the task "Power on VM". The admin could also use the power on task in a "Change RAM" request by using a "Power Off VM", "Change RAM on VM", and "Power On VM" tasks, in that order. vLaunch will step through each task, completing the larger goal. The "Change RAM on VM" task requires an amount of RAM for the VM. Thus, the form the user sees asks for a VM's name and an amount of RAM.</p>
		<p>In addition to generating the form, it dynamically creates the arguments which get passed to the tasks's script. This ensures that, as long as an admin reads the documentation, each admin can create their own custom requests and tasks for users. Since the scripts are seperate from vLaunch, they can be written in whichever language is easiest for the admin. It is currently running scripts in Java, Python and Ruby.</p>
		<p>vLaunch is also designed to work across many different locations. It is specifically designed to give admins the ability to customize, as well as appropriately segments permissions. Users can be approved to use multiple locations, based on admin discression. </p>
	</div>
</div>
<br />
<div class="row">
	<h4>Time Logging and Reporting</h4>
	<div class="col-md-5">
		<%=image_tag("timesheet.png", alt:"Timesheet Graph", class:"col-md-12")%>
	</div>
	<div class="col-md-7">
		<p>The robotics team got tired of trying to keep track of student hours on paper so we built a program to do so. Students sign in at the beginning of meetings with a barcode scanner and out at the end of the meeting.</p>

		<p>It has adjustable variables for requirements (# hours/#meetings attended) as well as many others (see the documentation for more). We've also set it up to provide graphs and statistics for when schools or sponsors ask.</p> 

		<p>You can find the code on <a href="https://github.com/FRC900/timesheet" target="_blakn">Github</a>.</p> 

		<p>There is also an example website set up on <a href="http://frctimesheet.herokuapp.com/" target="_blakn">Heroku</a>. 
		<li>Admin account - admin@900.com / zebracorns</li>
		<li>Student account - test@900.com / zebra</li>
		Feel free to play around and create items, please just don't delete or edit these two users. </p>

		<p>Our current setup is a Raspberry Pi hooked up to a monitor and a barcode scanner. It's been working great for us.</p>
	</div>
</div>
<br />
<div class="row">
	<h4>Team 900 Website</h4>
	<div class="col-md-5">
		<%=image_tag("Team900Website.png", alt:"Team Website", class:"col-md-12")%>
	</div>
	<div class="col-md-7">
		<p>The robotics team had a very out-dated website which wasn't being maintained. Last year, I rebuilt the site in Ruby on Rails. </p>

		<p>The site is very designed as a customized CMS. The students can easily log in and create blog entries, set meeting times or create new pages. </p> 
		<p>The slide show on the home page is pulled from a Google Plus Photo album. When the students want to change which photos appear, they can simply copy new photos into the album or remove photos. Since we use Google to manage our photos, this works out very well.</p>
		<p>Come check out the website: <a href="http://www.team900.org" target="_blakn">Team900.org</a>.</p>
	</div>
</div>
<br />
<br /><br />

app/views/pages/resume.html.erb
<h1>Pages#resume</h1>
<p>Find me in app/views/pages/resume.html.erb</p>

app/views/pages/robots.html.erb
<h1 class="text-pink text-center">Robots!</h1>
<div class="col-md-5">
	<p>
		After work, I mentor a FIRST Robotics Competition Team, Team 900 - The Zebracorns. The robotics team teaches students programming, advanced manufacturing, Computer Aided Design, time management, and project management.  In addition to learning these valuable skills, our students go to events all over the triangle to promote STEM education to other students of all ages.
	</p>
	<p>
		Starting in August, the students learn as much as they can to help prepare for the coming year's challenge.  Lessons on tool use occur simultaneously with discussions on advanced video processing, computer aided design, and fund-raising.
	</p>
	<p>
		On the first Saturday in January, FIRST (For Inspiration and Recognition of Science and Technology) releases the challenge for that year. The students then spend the next 6 weeks brainstorming, designing, building, programming and testing the robot. It's insane!
	</p>
	<p>
		The competitions are a cross between a sporting event and a festival. Teams from all over the world come dressed up in their team costumes, loud music is played and there is never enough time for sleeping. Among the commotion and spectacle, students are busy competing, repairing robots between matches, completing detailed statistical analysis on the other teams at the event, and talking about their passions with other students.
	</p>
</div>
<div class="col-md-7">
	<div id="carousel-robots" class="carousel slide" data-ride="carousel" >
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#carousel-robots" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel-robots" data-slide-to="1"></li>
	    <li data-target="#carousel-robots" data-slide-to="2"></li>
		<li data-target="#carousel-robots" data-slide-to="3"></li>
		<li data-target="#carousel-robots" data-slide-to="4"></li>
		<li data-target="#carousel-robots" data-slide-to="5"></li>
		<li data-target="#carousel-robots" data-slide-to="6"></li>
	  </ol>

	  <!-- Wrapper for slides -->
	  <div class="carousel-inner" role="listbox" >
	    <div class="item active">
			<%=image_tag("Outreach2.jpg", alt:"Teaching kids about robots")%>
	      	<div class="carousel-caption">
	        	Teaching kids about robots
	      	</div>
	    </div>
	    <div class="item">
	      <%=image_tag("BlueBanner.jpg", alt:"BlueBanner")%>
	      <div class="carousel-caption">
	        First Place aliance, North Carolina Regional, 2014
	      </div>
	    </div>
	    <div class="item">
	      <%=image_tag("Championships.jpg", alt:"championships")%>
	      <div class="carousel-caption">
	        FIRST World Championships, St. Louis 2014
	      </div>
	    </div>
	    <div class="item">
	      <%=image_tag("Outreach.jpg", alt:"Robotics Outreach")%>
	      <div class="carousel-caption">
	        Teaching kids about robots
	      </div>
	    </div>
	    <div class="item">
	      <%=image_tag("CityMuseum.jpg", alt:"City Museum")%>
	      <div class="carousel-caption">
	        Hanging around the City Museum in St Louis, 2014
	      </div>
	    </div>
	    <div class="item">
	      <%=image_tag("ExplainRobot.jpg", alt:"Explaining Robots")%>
	      <div class="carousel-caption">
	        Explaining robots
	      </div>
	    </div>
	    <div class="item">
	      <%=image_tag("DinnerRobots.jpg", alt:"Robotics Team Dinner")%>
	      <div class="carousel-caption">
	        Dinner with the team
	      </div>
	    </div>
	  </div>

	  <!-- Controls -->
	  <a class="left carousel-control" href="#carousel-robots" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#carousel-robots" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
	<script>
	$('.carousel').carousel({
	  interval: 5000
	})
	</script>
</div>

app/views/pages/sewing.html.erb
<h1 class="text-pink text-center">Sewing Projects</h1>
<div class="col-md-4">
	<p>
		In the little free time I have between work and robotics, I enjoy getting my hands dirty working on projects. Halloween is always an excellent excuse for a sewing project.  At least I'm getting better!
	</p>
</div>
<div class="col-md-4">	
	<div id="carousel-sewing" class="carousel slide" data-ride="carousel" >
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#carousel-sewing" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel-sewing" data-slide-to="1"></li>
	    <li data-target="#carousel-sewing" data-slide-to="2"></li>
		<li data-target="#carousel-sewing" data-slide-to="3"></li>
	  </ol>

	  <!-- Wrapper for slides -->
	  <div class="carousel-inner" role="listbox" >
	    <div class="item active">
			<%=image_tag("Khaleesi.jpg", alt:"Khaleesi", style:"height:500px")%>
	      	<div class="carousel-caption">
	        	Khaleesi from Game of Thrones, Halloween 2013
	      	</div>
	    </div>
	    <div class="item">
	      <%=image_tag("Medusa.JPG", alt:"Medusa", style:"height:500px")%>
	      <div class="carousel-caption">
	        Medusa, Halloween 2012
	      </div>
	    </div>
	    <div class="item">
	      <%=image_tag("Persephone.JPG", alt:"Persephone", style:"height:500px")%>
	      <div class="carousel-caption">
	        Persephone, Halloween 2010
	      </div>
	    </div>
	    <div class="item">
	      <%=image_tag("PeterPan.JPG", alt:"Peter Pan", style:"height:500px")%>
	      <div class="carousel-caption">
	        Peter Pan worn by Ragan, Halloween 2010
	      </div>
	    </div>
	  </div>

	  <!-- Controls -->
	  <a class="left carousel-control" href="#carousel-sewing" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#carousel-sewing" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
	<script>
	$('.carousel').carousel({
	  interval: 5000
	})
	</script>
</div>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag params[:controller] %>
<div>
	<div class="col-md-5" style="-webkit-transition: none;-webkit-transition: none; transition: none; background-color: rgba(255, 255, 255, 0.74902);">
		<div class="col-md-1">
		</div>
		<div class="col-md-10">
			<div class="row">
				<h3>Megan Wenzinger</h3>
				<p>I am a programmer by trade and a maker at heart. I love programming because it's like solving a giant puzzle with many solutions - trying to find the right piece to most elegantly solve the next problem, and the project as a whole.</p>
				<p>In my spare time, I mentor a high shool robotics team in Durham. I have also been volunteering at Maker Faire North Carolina since it's first year. When not busy with work, robots and MFNC, I enjoy sewing, woodworking, reading and being in nature. </p>
			</div>
			<br />
			<div class="row">
				<h4>Contact Me</h4>
				<div class="col-md-2">
					<a href="mailto:contact@MegWenzinger.com" target="_blank"><%=fa_icon("envelope fw 3x")%></a>
				</div>
				<div class="col-md-2">
					<a href="https://www.linkedin.com/pub/megan-wenzinger/27/726/270" target="_blank"><%=fa_icon("linkedin fw 3x")%></a>
				</div>
				<div class="col-md-2">
					<a href="https://plus.google.com/+MegWenzinger" target="_blank"><%=fa_icon("google-plus fw 3x")%></a>
				</div>
				<div class="col-md-2">
					<a href="https://www.facebook.com/mnwenzinger" target="_blank"><%=fa_icon("facebook fw 3x")%></a>
				</div>
			</div>
		</div>
	</div>
</div>